=== fernandoalvarezfp/Ejercicios-XSD/Librería/libreria.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libreria">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="articulo" type="tipoArticulo" />
                <xs:element name="editorial" type="tipoEditorial"/>
            </xs:choice>
        </xs:complexType>
        <xs:key name="tipoIDEd">
            <xs:selector xpath="editorial"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="idEditorial" refer="tipoIDEd">
            <xs:selector xpath="articulo"/>
            <xs:field xpath="@editorial"/>
        </xs:keyref>
    </xs:element>
    <xs:complexType name="tipoArticulo">
        <xs:sequence>
            <xs:element name="titulo" type="xs:string"/>
            <xs:element name="autor" type="xs:string"/>
            <xs:element name="paginas" type="xs:short"/>
            <xs:element name="genero" type="xs:string"/>
            <xs:element name="fechaLanzamiento" type="tipoFecha"/>
            <xs:element name="sinopsis" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="isbn" type="tipoIS"/>
        <xs:attribute name="precio" type="tipoPrecio"/>
        <xs:attribute name="editorial" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="tipoEditorial">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="direccion" type="xs:string"/>
            <xs:element name="tlf">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{9}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="tipoID"/>
    </xs:complexType>
    <xs:complexType name="tipoFecha">
        <xs:attribute name="aÃ±o">
            <xs:simpleType>
                <xs:restriction base='xs:short'>
                    <xs:totalDigits value="4"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="mes">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="Enero"/>
                    <xs:enumeration value="Febrero"/>
                    <xs:enumeration value="Marzo"/>
                    <xs:enumeration value="Abril"/>
                    <xs:enumeration value="Mayo"/>
                    <xs:enumeration value="Junio"/>
                    <xs:enumeration value="Julio"/>
                    <xs:enumeration value="Agosto"/>
                    <xs:enumeration value="Septiembre"/>
                    <xs:enumeration value="Octubre"/>
                    <xs:enumeration value="Noviembre"/>
                    <xs:enumeration value="Diciembre"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="dia">
            <xs:simpleType>
                <xs:restriction base='xs:short'>
                    <xs:minInclusive value="1"/>
                    <xs:maxInclusive value="31"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:simpleType name="tipoIS">
        <xs:restriction base="xs:unsignedLong">
            <xs:pattern value="\d{10,13}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoPrecio">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoID">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>  
</xs:schema>

=== fernandoalvarezfp/Ejercicios-XSD/Librería/libreria.xml
<?xml version="1.0" encoding="UTF-8"?>
<libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="libreria.xsd">
<articulo isbn='9788419266286' precio='22.00' editorial='H03'>
    <titulo>Babel</titulo>
    <autor>R.F. Kuang</autor>
    <paginas>700</paginas>
    <genero>Narrativa fantástica</genero>
    <fechaLanzamiento año='2022' mes='Noviembre' dia='28'/>
    <sinopsis>1828. El Instituto Real de Traducción de Oxford, también conocido como Babel, 
    es la institución mágica más importante del mundo. La magia con plata capaz de revelar...</sinopsis>
</articulo>
<articulo isbn='9788413143941' precio='14.95' editorial='B01'>
    <titulo>El camino de los reyes</titulo>
    <autor>Brandon Sanderson</autor>
    <paginas>1200</paginas>
    <genero>Narrativa fantástica</genero>
    <fechaLanzamiento año='2022' mes='Abril' dia='7'/>
</articulo>
<editorial id='H03'>
    <nombre>Hidra</nombre>
    <direccion>Cuevas, 27-3ºA. 28039 MADRID</direccion>
    <tlf>915715427</tlf>
</editorial>
<editorial id='B01'>
    <nombre>B de Bolsillo</nombre>
    <direccion>Calle Consell de Cent 425, 08009 BARCELONA</direccion>
    <tlf>934846600</tlf>
</editorial>
</libreria>
