=== fernandoalvarezfp/Ejercicios-XSD/Taller/exercicio2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="taller">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="coche" maxOccurs="unbounded"></xs:element>
                <xs:element name="empregado" type="tipoEmpregado"></xs:element>
                <xs:element name="traballo" type="tipoTraballo"></xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="identificador">
            <xs:selector xpath="empregado/mecánico"></xs:selector>
            <xs:field xpath="@id"></xs:field>
        </xs:key>
        <xs:keyref name="identificador2" refer="identificador">
            <xs:selector xpath="traballo/reparacion"></xs:selector>
            <xs:field xpath="@idempregado"></xs:field>
        </xs:keyref>
    </xs:element>

    <xs:group name="datos">
        <xs:choice>
            <xs:element name="nome" type="xs:string"></xs:element>
            <xs:element name="apelido1" type="xs:string"></xs:element>
            <xs:element name="apelido2" type="xs:string"></xs:element>
            <xs:element name="contacto" type="xs:integer"></xs:element>
        </xs:choice>
    </xs:group>

    <xs:complexType name="coche">
        <xs:sequence>
            <xs:element name="marca" type="xs:string"></xs:element>
            <xs:element name="modelo" type="xs:string"></xs:element>
            <xs:element name="cor" type="xs:string"></xs:element>
            <xs:element name="propietario" type="xs:string"></xs:element>
        </xs:sequence>
        <xs:attribute name="matrícula" use="required"></xs:attribute>
    </xs:complexType>

    <xs:element name="propietario">
        <xs:complexType>
            <xs:group ref="datos" maxOccurs="unbounded"></xs:group>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tipoEmpregado">
        <xs:sequence>
            <xs:element name="mecánico" type="tipoMecánico" maxOccurs="unbounded"></xs:element>
            <xs:element name="recepcionista" type="tipoRecepcionista" maxOccurs="1"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoMecánico">
        <xs:group ref="datos" maxOccurs="unbounded"></xs:group>
        <xs:attribute name="id" type="tipoIdEmpregado" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="tipoRecepcionista">
        <xs:group ref="datos" maxOccurs="unbounded"></xs:group>
        <xs:attribute name="id" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="tipoTraballo">
        <xs:choice>
            <xs:element name="reparacion" type="tipoReparacion" maxOccurs="unbounded"></xs:element>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="tipoReparacion">
        <xs:sequence>
            <xs:element name="praca" type="xs:string"></xs:element>
            <xs:element name="peza" type="xs:string"></xs:element>
            <xs:element name="tempo" type="tipoTempo"></xs:element>
            <xs:element name="preitv" type="tipoPreitv"></xs:element>
        </xs:sequence>
        <xs:attribute name="idempregado" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="tipoTempo">
        <xs:attribute name="horas" type="xs:integer"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="tipoPreitv">
        <xs:attribute name="realizada" type="xs:string" fixed="SÍ"></xs:attribute>
    </xs:complexType>

    <xs:simpleType name="tipoIdEmpregado">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][0-9]{3}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== fernandoalvarezfp/Ejercicios-XSD/Taller/exercicio.xml
<?xml version="1.0" encoding="UTF-8"?>
<taller xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="exercicio2.xsd">
    <coche matrícula="2638BGG">
        <marca>Alfa Romeo</marca>
        <modelo>Giulietta</modelo>
        <cor>Negro</cor>
        <propietario>
            <nome>Martín</nome>
            <apelido1>González</apelido1>
            <apelido2>Pereira</apelido2>
            <contacto>684315247</contacto>
        </propietario>
    </coche>
    <coche matrícula="5499JKL">
        <marca>Citroën</marca>
        <modelo>C3 Aircross</modelo>
        <cor>Rojo</cor>
        <propietario>
            <nome>Ramón</nome>
            <apelido1>Suárez</apelido1>
            <apelido2>Bernardez</apelido2>
            <contacto>654318526</contacto>
        </propietario>
    </coche>
    <empregado>
        <mecánico id="M542">
            <nome>Xosé</nome>
            <apelido1>Martínez</apelido1>
            <apelido2>Ramírez</apelido2>
            <contacto>612485749</contacto>
        </mecánico>
        <mecánico id="M866">
            <nome>Eva</nome>
            <apelido1>Paez</apelido1>
            <apelido2>Mariño</apelido2>
            <contacto>634512789</contacto>
        </mecánico>
        <recepcionista id="R222">
            <nome>Noelia</nome>
            <apelido1>Sánchez</apelido1>
            <apelido2>Bustelo</apelido2>
            <contacto>661543295</contacto>
        </recepcionista>
    </empregado>
    <traballo>
        <reparacion idempregado="M542">
            <praca>2638BGG</praca>
            <peza>Parachoque dianteiro</peza>
            <tempo horas="2"></tempo>
            <preitv realizada="SÍ"></preitv>
        </reparacion>
        <reparacion idempregado="M866">
            <praca>5499JKL</praca>
            <peza>Motor</peza>
            <tempo horas="16"></tempo>
            <preitv realizada="SÍ"></preitv>
        </reparacion>
    </traballo>
</taller>
