=== fernandoalvarezfp/Ejercicios-XSD/Tecnología/tecnologia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="empresa">
        <xs:complexType >
            <xs:choice maxOccurs="unbounded">
                <xs:element name="local" type="tipoLocal"></xs:element>
                <xs:element name="articulo" type="tipoArticulo"></xs:element>
                <xs:element name="proveedor" type="tipoProveedor"></xs:element>
                
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tipoLocal">
        <xs:sequence>
            <xs:element name="lugar" type="xs:string"></xs:element>
            <xs:element name="codPostal" type="tipoCodPostal"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoArticulo">
        <xs:sequence>
            <xs:element name="marca" type="xs:string"></xs:element>
            <xs:element name="modelo" type="xs:string"></xs:element>
            <xs:element name="precio" type="xs:double"></xs:element>
            <xs:element name="aÃ±osGarantia" type="xs:double" minOccurs="0" maxOccurs="15"></xs:element>
        </xs:sequence>
        <xs:attribute name="tipo" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="tipoProveedor">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"></xs:element>
            <xs:element name="telefono" type="tipoTelefono"></xs:element>
        </xs:sequence>
        <xs:attribute name="codigoPais" type="tipoCodigoPais"></xs:attribute>
        <xs:attribute name="ciudad" type="xs:string"></xs:attribute>
    </xs:complexType>
    
    <xs:simpleType name="tipoCodigoPais">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoTelefono">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\d{2,3})\s\d{9}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoCodPostal">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{5}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== fernandoalvarezfp/Ejercicios-XSD/Tecnología/tecnologia.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="tecnologia.xsd">
    <local>
        <lugar>Cambados</lugar>
        <codPostal>36630</codPostal>
    </local>
    <local>
        <lugar>Vilanova</lugar>
        <codPostal>36627</codPostal>
    </local>
    <articulo tipo="ordenador">
        <marca>MSI</marca>
        <modelo>Pulse</modelo>
        <precio>1348.99</precio>
        <a単osGarantia>5</a単osGarantia>
    </articulo>
    <articulo tipo="movil">
        <marca>Apple</marca>
        <modelo>Iphone 13</modelo>
        <precio>819.99</precio>
        <a単osGarantia>10</a単osGarantia>
    </articulo>
    <articulo tipo="auriculares">
        <marca>Xiaomi</marca>
        <modelo>Redmi Buds</modelo>
        <precio>33.99</precio>
    </articulo>
    <proveedor codigoPais="ESP" ciudad="Vilagarcia">
        <nombre>Plexus</nombre>
        <telefono>34 681612868</telefono>
    </proveedor>
    <proveedor codigoPais="ITA" ciudad="Napoles">
        <nombre>Itatecno</nombre>
        <telefono>393 681686868</telefono>
    </proveedor>
</empresa>
